services:
  - type: web
    name: cookbook-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: cookbook-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: cookbook-redis
          property: connectionString
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: JWT_REFRESH_SECRET
        fromSecret: JWT_REFRESH_SECRET

databases:
  - name: cookbook-db
    databaseName: cookbook_connect
    user: cookbook_user

  - name: cookbook-redis
    type: redis
