export const ERROR_CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',

  // Resources
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // External Services
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  ELASTICSEARCH_ERROR: 'ELASTICSEARCH_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  OPENAI_ERROR: 'OPENAI_ERROR',

  // Business Logic
  RECIPE_NOT_FOUND: 'RECIPE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RATING_ALREADY_EXISTS: 'RATING_ALREADY_EXISTS',
  FOLLOW_ALREADY_EXISTS: 'FOLLOW_ALREADY_EXISTS',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
